/**
 * @author Russell Toris - rctoris@wpi.edu
 */

var ROS3D = ROS3D || {
  REVISION : '1'
};

// URDF types
ROS3D.URDF_SPHERE = 0;
ROS3D.URDF_BOX = 1;
ROS3D.URDF_CYLINDER = 2;
ROS3D.URDF_MESH = 3;

// Marker types
ROS3D.MARKER_ARROW = 0;
ROS3D.MARKER_CUBE = 1;
ROS3D.MARKER_SPHERE = 2;
ROS3D.MARKER_CYLINDER = 3;
ROS3D.MARKER_LINE_STRIP = 4;
ROS3D.MARKER_LINE_LIST = 5;
ROS3D.MARKER_CUBE_LIST = 6;
ROS3D.MARKER_SPHERE_LIST = 7;
ROS3D.MARKER_POINTS = 8;
ROS3D.MARKER_TEXT_VIEW_FACING = 9;
ROS3D.MARKER_MESH_RESOURCE = 10;
ROS3D.MARKER_TRIANGLE_LIST = 11;